[workspace]
resolver = "2"
members = [
    "crates/trt-sys",
    "crates/trt",
    "crates/trt-preproc",
    "crates/trt-xfeat",
    "crates/trt-yolo",
    "crates/trt-gst",
    "crates/nvbuf-sys",
    "examples/rtsp_yolo",
    "examples/rtsp_xfeat",
]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
authors = ["Edgar Riba <edgar.riba@gmail.com>"]
