//! Raw FFI bindings to TensorRT 10.x.
//!
//! ## Architecture
//!
//! All bindings go through a hand-written pure-C bridge:
//! - `include/trt_bridge.h` — opaque `btrt_*_t*` handle API (no TRT/CUDA headers leak out)
//! - `src/logger_shim.cpp` — the ONLY unavoidable C++: `ShimLogger : public nvinfer1::ILogger`
//!   (Rust cannot subclass abstract C++ classes)
//! - `src/trt_bridge.cpp` — thin C wrappers over TRT runtime/engine/context/CUDA
//!
//! bindgen generates Rust FFI from `trt_bridge.h`. When TRT updates:
//! 1. `apt install` new TRT headers
//! 2. `cargo build -p trt-sys` — C++ compiler errors in trt_bridge.cpp point exactly to
//!    changed methods (enqueueV2→V3, Dims→Dims64, etc.)
//! 3. Fix those methods; bindgen regenerates the Rust side automatically
//! See UPDATING.md for the full checklist.

#![allow(unsafe_code)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]

// btrt_* C bridge bindings (logger shim + runtime/engine/context/CUDA)
// Generated by bindgen from include/trt_bridge.h (includes logger_shim.h).
// This is the complete stable API consumed by the `trt/` safe-wrapper crate.
include!(concat!(env!("OUT_DIR"), "/bridge_bindings.rs"));

// In-process ONNX -> engine builder (feature = "builder", links nvonnxparser).
#[cfg(feature = "builder")]
include!(concat!(env!("OUT_DIR"), "/builder_bindings.rs"));

// ── Version constants ────────────────────────────────────────────────────────

/// Installed TensorRT version "MAJOR.MINOR.PATCH.BUILD", parsed from
/// NvInferVersion.h at build time.  Engine-cache keys depend on this.
pub const TENSORRT_VERSION: &str = env!("TENSORRT_VERSION");

/// Returns `true` if `status` indicates success (status == 0).
#[inline]
pub fn is_ok(status: i32) -> bool {
    status == 0
}
