[package]
name = "trt-rs-gst"
version.workspace = true
edition.workspace = true
repository.workspace = true
publish = false

[lib]
name = "trt_gst"

[dependencies]
nvbuf-sys     = { path = "../nvbuf-sys" }
gstreamer     = "0.20"
gstreamer-app = "0.20"
trt-rs        = { path = "../trt" }
trt-rs-preproc = { path = "../trt-preproc" }
thiserror     = "2.0"
cudarc        = { version = "0.17", features = ["cuda-12060"] }
