//! Auto-generated FFI bindings to TensorRT 10.x.
//!
//! ## Architecture
//!
//! This crate uses two complementary binding strategies:
//!
//! ### 1. autocxx — auto-generated C++ type bindings
//! The `include_cpp!` block below tells autocxx to generate Rust wrappers for
//! TRT C++ types directly from the TRT headers. When TRT updates, recompile and
//! get Rust errors exactly where the API changed.
//!
//! ### 2. btrt_* C bridge — hand-compiled bridge (bindgen)
//! The `btrt_*` functions in `src/logger_shim.cpp` and `src/trt_bridge.cpp`
//! wrap the TRT C++ API as pure-C functions for the `trt/` safe-wrapper crate.
//!
//! ## The ONLY reason for hand-written C++
//! `src/logger_shim.cpp` — Rust cannot subclass abstract C++ classes.
//! `ILogger` is abstract and must be subclassed; the shim does this once.
//!
//! ## Updating for a new TRT version
//! 1. Install new TRT headers (apt)
//! 2. `cargo build -p trt-sys` — autocxx regenerates all type bindings
//! 3. Fix Rust compile errors (they tell you exactly what TRT API changed)
//! 4. If `ILogger::log()` signature changed, fix `src/logger_shim.cpp`
//! See UPDATING.md in the repo root for the full checklist.

#![allow(unsafe_code)]
#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(clippy::all)]

use autocxx::prelude::*;

// ── autocxx: auto-generated bindings from TRT C++ headers ──────────────────
// When TRT updates, this block auto-regenerates from the new headers.
// Rust compile errors below = TRT API changed = update trt_bridge.cpp.
//
// Notes on what we generate:
//   - Dims64: the core shape type in TRT 10 (int64_t dims[8])
//   - DataType, TensorIOMode: enums used at the Rust API boundary
//   - IRuntime, ICudaEngine, IExecutionContext: abstract interfaces;
//     you receive these via btrt_* factory functions, not by constructing them.
//
// Intentionally NOT generated:
//   - createInferRuntime_INTERNAL: extern "C" global (not in nvinfer1::),
//     handled by trt_bridge.cpp via btrt_runtime_create().
//   - ILogger: abstract class that must be subclassed (see logger_shim.cpp).
include_cpp! {
    #include "NvInferRuntime.h"
    #include "NvInferRuntimeBase.h"
    safety!(unsafe_ffi)

    // Dims type used throughout TRT 10 (int64_t dims[8])
    generate!("nvinfer1::Dims64")

    // Enums exposed at the Rust API boundary
    generate!("nvinfer1::DataType")
    generate!("nvinfer1::TensorIOMode")

    // Interfaces — autocxx generates wrappers for their virtual methods.
    // You receive these as raw C++ pointers from btrt_* factory functions.
    generate!("nvinfer1::IRuntime")
    generate!("nvinfer1::ICudaEngine")
    generate!("nvinfer1::IExecutionContext")
}

// ── btrt_* C bridge bindings (logger shim + runtime/engine/context/CUDA) ───
// Generated by bindgen from include/trt_bridge.h (which includes logger_shim.h).
// This is the stable API consumed by the `trt/` safe-wrapper crate.
include!(concat!(env!("OUT_DIR"), "/bridge_bindings.rs"));

// ── Version constants ────────────────────────────────────────────────────────
pub const TENSORRT_VERSION_MAJOR: u32 = 10;
pub const TENSORRT_VERSION_MINOR: u32 = 3;
pub const TENSORRT_VERSION_PATCH: u32 = 0;
pub const TENSORRT_VERSION_BUILD: u32 = 30;

/// Convenience: returns `true` if `status` indicates success (status == 0).
#[inline]
pub fn is_ok(status: i32) -> bool {
    status == 0
}
