[package]
name = "rtsp_xfeat"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
trt       = { path = "../../crates/trt" }
trt-xfeat = { path = "../../crates/trt-xfeat" }
trt-gst   = { path = "../../crates/trt-gst" }
env_logger = "0.11"
image      = "0.25"
trt-hub    = { path = "../../crates/trt-hub", features = ["builder"] }
