[package]
name = "rtsp_xfeat"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
trt-rs       = { path = "../../crates/trt" }
trt-rs-xfeat = { path = "../../crates/trt-xfeat" }
trt-rs-gst   = { path = "../../crates/trt-gst" }
env_logger = "0.11"
image      = "0.25"
trt-rs-hub   = { path = "../../crates/trt-hub", features = ["builder"] }
