[package]
name = "rtsp_xfeat"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
vision-rt    = { path = "../../crates/vrt" }
vrt-xfeat    = { path = "../../crates/vrt-xfeat" }
vrt-gst      = { path = "../../crates/vrt-gst" }
env_logger = "0.11"
image      = "0.25"
vrt-hub      = { path = "../../crates/vrt-hub", features = ["builder"] }
